# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
DISABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_SECRETLINT
  - REPOSITORY_SYFT
  - REPOSITORY_TRIVY
  - SPELL_CSPELL
  - COPYPASTE_JSCPD
  - REPOSITORY_GIT_DIFF
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: \.github|megalinter-reports
SHOW_ELAPSED_TIME: true
GITHUB_STATUS_REPORTER: true
